
import base64

# Parts of the backtest script, base64 encoded to avoid shell issues
parts = []

# Part: main logic
parts.append(base64.b64decode(
    'Y29ubiA9IHNxbGl0ZTMuY29ubmVjdChEQikKY3VyID0gY29ubi5jdXJzb3IoKQpjdXIuZXhlY3V0ZSgnU0VMRUNUIERJU1RJTkNUIGRhdGUgRlJPTSBudG1fc2NyZWVuaW5nIE9SREVSIEJZIGRhdGUnKQpkYXRlcyA9IFtyWzBdIGZvciByIGluIGN1ci5mZXRjaGFsbCgpXQpwcmludChmJ0RhdGVzOiB7bGVuKGRhdGVzKX0nKQpmb3IgZCBpbiBkYXRlczogcHJpbnQoZicgIHtkfScpCnByaW50KCkKcmVzID0geydBJzogeyd0NSc6W10sICd0MTAnOltdLCAndDMwJzpbXX0sICdCJzogeyd0NSc6W10sICd0MTAnOltdLCAndDMwJzpbXX19CmRldGFpbHMgPSBbXQpkaXNhZ3JlZSA9IHsnb0EnOltdLCAnb0InOltdfQo='
).decode())

print(parts[0][:60])
print('Builder works')
